Repository PedroHBachiega/avaliacao-tp2-helpapp, pull requests merged in 2025-06, with the labels that each got.

#130 test: adiciona testes unitários para UsersController
  StockApp.API.Test/Controllers/UsersControllerTests.cs
  StockApp.API.Test/StockApp.API.Test.csproj
  StockApp.API.Test/UnitTest1.cs
  StockApp.API.Test/Usings.cs
  StockApp.API/Controllers/UsersController.cs
  StockApp.Application/DTOs/UserRegisterDTO.cs
  StockApp.Application/Interfaces/IUserService.cs
  StockApp.sln
Labels: enhancement

#132 Configuração de Cors no Program.cs
  StockApp.API/Program.cs
Labels: enhancement

#133 Criação do Controlador UserController e Endpoint para Criar Usuário
  StockApp.API/Controllers/UserController.cs
  StockApp.API/Program.cs
  StockApp.Application/Interfaces/IUserService.cs
  StockApp.Application/Services/UserService.cs
Labels: enhancement

#139 feat: adiciona entidade Supplier com validações no domínio
  StockApp.Domain/Entities/Supplier.cs
Labels: enhancement

#140 feat: cria interface de repositório para Supplier
  StockApp.Domain/Interfaces/ISupplierRepository.cs
Labels: enhancement

#143 fix: correções em SuppliersController e Repository
  StockApp.Application/DTOs/CategoryDTO.cs
  StockApp.Domain/Interfaces/IStockRepository.cs
  StockApp.Domain/Interfaces/ISupplierRepository.cs
Labels: bug

#150 feat: Implementação do sistema de rastreamento de entregas com mock
  StockApp.API/Controllers/DeliveryController.cs
  StockApp.Application/DTOs/DeliveryInfoDTO.cs
  StockApp.Application/Interfaces/IDeliveryService.cs
  StockApp.Application/Services/DeliveryService.cs
  StockApp.Infra.IoC/DependencyInjectionAPI.cs
  StockApp.Infra.IoC/StockApp.Infra.IoC.csproj
Labels: enhancement

#152 Implementando Paginação nos Endpoints de Leitura
  StockApp.API/Controllers/CategoriesController.cs
  StockApp.API/Controllers/ProductsController.cs
  StockApp.API/Controllers/SuppliersController.cs
  StockApp.Application/DTOs/PagedResult.cs
  StockApp.Application/DTOs/PaginationParameters.cs
  StockApp.Application/Interfaces/ICategoryService.cs
  StockApp.Application/Interfaces/IProductService.cs
  StockApp.Application/Interfaces/ISupplierService.cs
  StockApp.Application/Mappings/DomainToDTOMappingProfile.cs
  StockApp.Application/Services/CategoryService.cs
  StockApp.Application/Services/ProductService.cs
  StockApp.Application/Services/SupplierService.cs
  StockApp.Domain/Interfaces/ICategoryRepository.cs
  StockApp.Domain/Interfaces/IProductRepository.cs
  StockApp.Domain/Interfaces/ISupplierRepository.cs
  StockApp.Infra.Data/Repositories/CategoryRepository.cs
  StockApp.Infra.Data/Repositories/ProductRepository.cs
  StockApp.Infra.Data/Repositories/SupplierRepository.cs
  StockApp.Infra.IoC/DependencyInjectionAPI.cs
Labels: good first issue

#156 Criação do Serviço de Autenticação JWT
  StockApp.API/Controllers/TokenController.cs
  StockApp.API/Program.cs
  StockApp.Application/DTOs/TokenResponseDto.cs
  StockApp.Application/DTOs/UserLoginDTO.cs
  StockApp.Application/Interfaces/IAuthService.cs
  StockApp.Domain/Interfaces/IUserRepository.cs
  StockApp.Infra.Data/Identity/AuthService.cs
  StockApp.Infra.Data/Repositories/UserRepository.cs
  StockApp.Infra.Data/StockApp.Infra.Data.csproj
  StockApp.Infra.IoC/DependencyInjectionAPI.cs
Labels: enhancement

#159 feat: implementa busca por fornecedores com filtros de nome e email
  StockApp.API/Controllers/SuppliersController.cs
  StockApp.Domain/Interfaces/ISupplierRepository.cs
  StockApp.Infra.Data/Repositories/SupplierRepository.cs
Labels: enhancement

#173 ConfigurandoTaxa de Limitação (Rate Limiting)
  StockApp.API.Test/RateLimitingMiddlewareTests.cs
  StockApp.API.Test/StockApp.API.Test.csproj
  StockApp.API/Controllers/RateLimitTestController.cs
  StockApp.API/Infrastructure/Middlewares/RateLimitingExtensions.cs
  StockApp.API/Infrastructure/Middlewares/RateLimitingMiddleware.cs
  StockApp.API/Program.cs
Labels: good first issue

#174 Adicionando Funcionalidade de Filtragem Avançada nos Relatórios
  StockApp.API/Controllers/ProductsController.cs
  StockApp.API/Controllers/ReportsController.cs
  StockApp.Application/DTOs/PagedResult.cs
  StockApp.Application/DTOs/ProductFilterDTO.cs
  StockApp.Application/DTOs/ProductSearchDTO.cs
  StockApp.Application/DTOs/ReportDTO.cs
  StockApp.Application/Interfaces/IProductService.cs
  StockApp.Application/Services/ProductService.cs
  StockApp.Domain/Interfaces/IProductRepository.cs
  StockApp.Infra.Data/Repositories/ProductRepository.cs
Labels: good first issue

#181 Adicionando comparação de produtos
  StockApp.API.Test/ProductComparisonTests.cs
  StockApp.API/Controllers/ProductsController.cs
  StockApp.API/wwwroot/product-comparison-test.html
  StockApp.Application/DTOs/ProductComparisonDTO.cs
  StockApp.Application/Interfaces/IProductService.cs
  StockApp.Application/Services/ProductService.cs
Labels: good first issue

#183 feat: Implementa Sistema de Gestão de Relacionamento com Fornecedores…
  StockApp.API/Controllers/SupplierRelationshipController.cs
  StockApp.Application/Interfaces/ISupplierRelationshipManagementService.cs
  StockApp.Application/Mappings/DomainToDTOMappingProfile.cs
  StockApp.Application/Services/SupplierRelationshipManagementService.cs
  StockApp.Infra.IoC/DependencyInjectionAPI.cs
Labels: enhancement

#185 Sistema de Relatórios com Gráficos
  StockApp.API/Controllers/ChartsController.cs
  StockApp.API/wwwroot/charts.html
  StockApp.Application/DTOs/ChartReportDTO.cs
  StockApp.Application/Interfaces/IReportService.cs
  StockApp.Application/Services/ReportService.cs
  StockApp.Infra.IoC/DependencyInjection.cs
Labels: good first issue

#186 feat: implementação completa do sistema de gestão de contratos
  StockApp.API.Test/ContractManagementServiceTests.cs
  StockApp.API.Test/Controllers/ContractsControllerTests.cs
  StockApp.API/Controllers/ContractsController.cs
  StockApp.Application/DTOs/ContractDto.cs
  StockApp.Application/DTOs/CreateContractDto.cs
  StockApp.Application/Interfaces/IContractManagementService.cs
  StockApp.Application/Mappings/DomainToDTOMappingProfile.cs
  StockApp.Application/Services/ContractManagementService.cs
  StockApp.Domain/Entities/Contract.cs
  StockApp.Domain/Enums/ContractType.cs
  StockApp.Domain/Interfaces/IContractRepository.cs
  StockApp.Infra.Data/Context/ApplicationDbContext.cs
  StockApp.Infra.Data/EntityConfiguration/ContractConfiguration.cs
  StockApp.Infra.Data/Repositories/ContractRepository.cs
  StockApp.Infra.IoC/DependencyInjectionAPI.cs
Labels: enhancement

#190 Criado Sistema de Descontos e Promoções
  StockApp.Application/DTOs/ProductDTO.cs
  StockApp.Application/Interfaces/IDiscountService.cs
  StockApp.Application/Services/DiscountService.cs
  StockApp.Domain/Entities/Product.cs
Labels: enhancement

#192 Adicionar Testes Unitários para o Controlador TokenController
  StockApp.API.Test/Controllers/TokenControllerTests.c.cs
Labels: enhancement

#193 Implementar Auditoria de Mudanças no Estoque
  StockApp.API/Controllers/ProductsController.cs
  StockApp.API/Program.cs
  StockApp.Application/Interfaces/IAuditService.cs
  StockApp.Domain/Entities/AuditLog.cs
  StockApp.Infra.Data/Context/ApplicationDbContext.cs
  StockApp.Infra.Data/Services/AuditService.cs
Labels: enhancement
